DROP TABLE TBL_CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE TBL_ACCOUNT CASCADE CONSTRAINTS;
DROP TABLE TBL_TRANSACTION CASCADE CONSTRAINTS;
DROP TABLE TBL_USER CASCADE CONSTRAINTS;
DROP SEQUENCE TBL_CUSTOMER_SEQ;
DROP SEQUENCE TBL_ACCOUNT_SEQ;
DROP SEQUENCE TBL_TRANSACTION_SEQ;

CREATE SEQUENCE TBL_CUSTOMER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE TBL_CUSTOMER (
    CUSTOMER_ID NUMBER(10,0),
    SSNID NUMBER(9,0) NOT NULL,
    FNAME VARCHAR2(20 BYTE) NOT NULL,
    LNAME VARCHAR2(20 BYTE) NOT NULL,
    DOB DATE NOT NULL,
    ADDRESS1 VARCHAR2(50 BYTE) NOT NULL,
    ADDRESS2 VARCHAR2(50 BYTE) NOT NULL,   
    CITY VARCHAR2(20 BYTE) NOT NULL,       
    STATE VARCHAR2(30 BYTE) NOT NULL,  
    ZIP_CODE VARCHAR2(6 BYTE) NOT NULL,
    STATUS VARCHAR2(8 BYTE) NOT NULL,
    LAST_UPDATE TIMESTAMP (6),  
    CONSTRAINT TBL_CUSTOMER_PK PRIMARY KEY (CUSTOMER_ID)
);

INSERT INTO TBL_CUSTOMER VALUES (1, 123456789, 'Bob', 'Smith', to_date('28-FEB-21', 'DD-MON-RR'), '56 Parker Ave', 'Apt 3D', 'Hartford', 'New Jersey', 'Q12W43', 'active', to_timestamp('30-NOV-22 04.18.00.956000000 PM', 'DD-MON-RR HH.MI.SSXFF AM'));

CREATE OR REPLACE TRIGGER TBL_CUSTOMER_TRG
  BEFORE INSERT ON TBL_CUSTOMER
  FOR EACH ROW
BEGIN
  SELECT TBL_CUSTOMER_SEQ.nextval
  INTO :new.CUSTOMER_ID
  FROM dual;
END;

/

CREATE SEQUENCE TBL_ACCOUNT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE TBL_ACCOUNT (
    ACCOUNT_ID NUMBER(10,0),
    CUSTOMER_ID NUMBER(10,0) NOT NULL,
    AC_TYPE VARCHAR2(10 BYTE) NOT NULL,
    BALANCE NUMBER(10,2) NOT NULL,
    STATUS VARCHAR2(6 BYTE) NOT NULL,
    LAST_UPDATE TIMESTAMP (6),
    CONSTRAINT TBL_ACCOUNT_PK PRIMARY KEY (ACCOUNT_ID),
    CONSTRAINT TBL_ACCOUNT_FK1 FOREIGN KEY (CUSTOMER_ID) REFERENCES TBL_CUSTOMER(CUSTOMER_ID)
);

CREATE OR REPLACE TRIGGER TBL_ACCOUNT_TRG
  BEFORE INSERT ON TBL_ACCOUNT
  FOR EACH ROW
BEGIN
  SELECT TBL_ACCOUNT_SEQ.nextval
  INTO :new.ACCOUNT_ID
  FROM dual;
END;

/

CREATE SEQUENCE TBL_TRANSACTION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE TBL_TRANSACTION (
    TRANSACTION_ID NUMBER(15,0),
    TRANSACTION_TIMESTAMP TIMESTAMP (6) NOT NULL,
    T_TYPE VARCHAR2(10 BYTE) NOT NULL,
    AMOUNT NUMBER(10,2) NOT NULL,
    FROM_AC_ID NUMBER(10,0) NOT NULL,
    TO_AC_ID NUMBER(10,0) NOT NULL,
    CONSTRAINT TBL_TRANSACTION_PK PRIMARY KEY (TRANSACTION_ID),
    CONSTRAINT TBL_TRANSACTION_FK1 FOREIGN KEY (FROM_AC_ID) REFERENCES TBL_ACCOUNT(ACCOUNT_ID),
    CONSTRAINT TBL_TRANSACTION_FK2 FOREIGN KEY (TO_AC_ID) REFERENCES TBL_ACCOUNT(ACCOUNT_ID)
);

CREATE OR REPLACE TRIGGER TBL_TRANSACTION_TRG
  BEFORE INSERT ON TBL_TRANSACTION
  FOR EACH ROW
BEGIN
  SELECT TBL_TRANSACTION_SEQ.nextval
  INTO :new.TRANSACTION_ID
  FROM dual;
END;

/

CREATE TABLE TBL_USER (
    USERNAME VARCHAR2(20 BYTE),
    PASSWORD VARCHAR2(50 BYTE) NOT NULL,
    FNAME  VARCHAR2(20 BYTE) NOT NULL,
    LNAME  VARCHAR2(20 BYTE) NOT NULL,
    ROLE  VARCHAR2(20 BYTE) NOT NULL,
    LAST_LOGIN_TIME TIMESTAMP (6) NOT NULL,
    CONSTRAINT TBL_USER_PK PRIMARY KEY (USERNAME)
);

INSERT INTO TBL_USER VALUES ('executive', 'executive123', 'John', 'Doe', 'executive', to_timestamp('30-NOV-22 05.12.25.656000000 PM', 'DD-MON-RR HH.MI.SSXFF AM'));
INSERT INTO TBL_USER VALUES ('teller', 'teller123', 'Jane', 'Doe', 'teller', to_timestamp('30-NOV-22 04.53.26.139000000 PM', 'DD-MON-RR HH.MI.SSXFF AM'));